/**
 * @license Copyright (c) 2003-2014, CKSource - Frederico Knabben. All rights reserved.
 * For licensing, see LICENSE.md or http://ckeditor.com/license
 */

var CKBUILDER_CONFIG = {
    skin: 'moono',
    preset: 'basic',
    ignore: [
        '.idea',
        'dev',
        'samples',
        '.gitignore',
        '.gitattributes',
        'CHANGES.md',
        'LICENSE.md',
        'README.md',
        '.mailmap',
        'skins/kama'
    ],
    plugins : {
        'backgrounds' : 1,
        'basicstyles' : 1,
        'button' : 1,
        'clipboard' : 1,
        'colorbutton' : 1,
        'colordialog' : 1,
        'contextmenu' : 1,
        'dialog' : 1,
        'dialogadvtab' : 1,
        'dialogui' : 1,
        'enterkey' : 1,
        'entities' : 1,
        'fakeobjects' : 1,
        'filebrowser' : 1,
        'find' : 1,
        'floatingspace' : 1,
        'floatpanel' : 1,
        'font' : 1,
        'format' : 1,
        'image2' : 1,
        'indent' : 1,
        'indentblock' : 1,
        'indentlist' : 1,
        'justify' : 1,
        'lineutils' : 1,
        'link' : 1,
        'list' : 1,
        'listblock' : 1,
        'liststyle' : 1,
        'maximize' : 1,
        'menu' : 1,
        'panel' : 1,
        'panelbutton' : 1,
        'pastefromword' : 1,
        'popup' : 1,
        'removeformat' : 1,
        'richcombo' : 1,
        'selectall' : 1,
        'showborders' : 1,
        'sourcearea' : 1,
        'specialchar' : 1,
        'table' : 1,
        'tableresize' : 1,
        'tabletools' : 1,
        'toolbar' : 1,
        'uicolor' : 1,
        'undo' : 1,
        'widget' : 1,
        'wysiwygarea' : 1,
        'youtube': 1
    },
    languages : {
        'en' : 1,
        'nl' : 1
    }
};
